// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// DirReader is an autogenerated mock type for the DirReader type
type DirReader struct {
	mock.Mock
}

// ReadDir provides a mock function with given fields: name
func (_m *DirReader) ReadDir(name string) ([]fs.DirEntry, error) {
	ret := _m.Called(name)

	var r0 []fs.DirEntry
	if rf, ok := ret.Get(0).(func(string) []fs.DirEntry); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
