// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FilepathGlober is an autogenerated mock type for the FilepathGlober type
type FilepathGlober struct {
	mock.Mock
}

// Glob provides a mock function with given fields: pattern
func (_m *FilepathGlober) Glob(pattern string) ([]string, error) {
	ret := _m.Called(pattern)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pattern)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
