// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ModtimeChecker is an autogenerated mock type for the ModtimeChecker type
type ModtimeChecker struct {
	mock.Mock
}

// ModifiedInTimeFrame provides a mock function with given fields: pth, start, end
func (_m *ModtimeChecker) ModifiedInTimeFrame(pth string, start time.Time, end time.Time) (bool, error) {
	ret := _m.Called(pth, start, end)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) bool); ok {
		r0 = rf(pth, start, end)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(pth, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
