// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	xcscheme "github.com/bitrise-io/go-xcode/xcodeproject/xcscheme"
)

// XcodeProject is an autogenerated mock type for the XcodeProject type
type XcodeProject struct {
	mock.Mock
}

// Scheme provides a mock function with given fields: pth, name
func (_m *XcodeProject) Scheme(pth string, name string) (*xcscheme.Scheme, error) {
	ret := _m.Called(pth, name)

	var r0 *xcscheme.Scheme
	if rf, ok := ret.Get(0).(func(string, string) *xcscheme.Scheme); ok {
		r0 = rf(pth, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*xcscheme.Scheme)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(pth, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
